import React from 'react'
import Head from 'next/head'

function CustomDocumentHead({ title }: { title: string }) {
    return (
        <Head>
            <title>{title ? `${title} | My Next Game` : 'My Next Game'}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default CustomDocumentHead