export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT';

//favorite game
export const USER_REQUEST_NEW_FAV_GAME = 'USER_REQUEST_NEW_FAV_GAME'
export const USER_SUCCESS_NEW_FAV_GAME = 'USER_SUCCESS_NEW_FAV_GAME'
export const USER_FAIL_NEW_FAV_GAME = 'USER_FAIL_NEW_FAV_GAME'

export const USER_REQUEST_REMOVE_FAV_GAME = 'USER_REQUEST_REMOVE_FAV_GAME'
export const USER_SUCCESS_REMOVE_FAV_GAME = 'USER_SUCCESS_REMOVE_FAV_GAME'
export const USER_FAIL_REMOVE_FAV_GAME = 'USER_FAIL_REMOVE_FAV_GAME'

export const USER_UPDATE_REQUEST_FAVORITE_GAMES = 'USER_UPDATE_REQUEST_FAVORITE_GAMES'
export const USER_UPDATE_SUCCESS_FAVORITE_GAMES = 'USER_UPDATE_SUCCESS_FAVORITE_GAMES'
export const USER_UPDATE_FAIL_FAVORITE_GAMES = 'USER_UPDATE_FAIL_FAVORITE_GAMES'

//NOTIFICATIONS 
export const NOTIFICATIONS_REQUEST = 'NOTIFICATIONS_REQUEST'
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS'
export const NOTIFICATIONS_FAIL = 'NOTIFICATIONS_FAIL'